/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : karan
 * Created : 11/19/2020 09:10:27
 */

package com.cg.capbrading.service;

import org.junit.*;
import static org.junit.Assert.*;
import com.cg.capbrading.service.VendorServiceImpl;
import com.cg.capbrading.entity.Vendor;
import java.util.List;



public class VendorServiceImplTest {
	
	static VendorService vendorServiceImpl; 

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
		// TODO add setup code.
		vendorServiceImpl = new VendorServiceImpl();
		Vendor vendor1 = new Vendor(1, null, null, null);
		vendorServiceImpl.addVendor(vendor1);
	}

	/**
	 *
	 * @see com.cg.capbrading.service.VendorServiceImpl#addVendor(Vendor)
	 */
	@Test
	public void addVendor() {
		Vendor vendor = new Vendor();
		vendorServiceImpl.addVendor(vendor);
	}

	/**
	 *
	 * @see com.cg.capbrading.service.VendorServiceImpl#deleteVendor(Vendor)
	 */
	@Test
	public void deleteVendor() {
		Vendor vendor = new Vendor();
		vendorServiceImpl.deleteVendor(vendor);
	}

	/**
	 *
	 * @see com.cg.capbrading.service.VendorServiceImpl#updateVendor(Vendor)
	 */
	@Test
	public void updateVendor() {
		Vendor vendor = new Vendor();
		vendorServiceImpl.updateVendor(vendor);
	}

	/**
	 *
	 * @see com.cg.capbrading.service.VendorServiceImpl#viewAllVendors()
	 */
	@Test
	public void viewAllVendors() {
		List<Vendor> result = vendorServiceImpl.viewAllVendors();
		
						
							assertTrue("result should be not null and not empty", result != null && !result.isEmpty());
	}

	
}
