/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : karan
 * Created : 11/19/2020 08:25:31
 */

package com.cg.capbrading.entity;

import org.junit.*;
import static org.junit.Assert.*;
import com.cg.capbrading.entity.Product;
import java.lang.String;



public class ProductTest {

	static Product product = new Product(null, null, 0, null);
	
	/**
	 *
	 * @see com.cg.capbrading.entity.Product#setId(int)
	 */
	@Test
	public void setId() {
		product.setId(1);
		Assert.assertEquals(1, product.getId());
	}
	
	/**
	 *
	 * @see com.cg.capbrading.entity.Product#getId()
	 */
	@Test
	public void getId() {
		product.setId(1);
		int id = product.getId();
		
						
							assertTrue("id should be greater than zero", id > 0);
	}

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
		product.setProductName("test");
		product.setBrand("brand");
		product.setPrice(1000);
		product.setCategory("Electronics");
	
	}

	/**
	 *
	 * @see com.cg.capbrading.entity.Product#getProductName()
	 */
	@Test
	public void getProductName() {
		String productname = product.getProductName();
		
						
							assertTrue("productname should be not null and equal to test", productname != null && !productname.equals(""));
	}

	/**
	 *
	 * @see com.cg.capbrading.entity.Product#getBrand()
	 */
	@Test
	public void getBrand() {
		String brand = product.getBrand();
		assertNotNull("brand cannot be null", brand);
	}

	/**
	 *
	 * @see com.cg.capbrading.entity.Product#getPrice()
	 */
	@Test
	public void getPrice() {
		double price = product.getPrice();
		
						
							assertTrue("price should be equal to 1000", price == 1000);
	}

	/**
	 *
	 * @see com.cg.capbrading.entity.Product#getCategory()
	 */
	@Test
	public void getCategory() {
		String category = product.getCategory();
		
						
							assertTrue("category should be not null and equal to Electronics", category != null && category.equals("Electronics"));
	}



	
}
