/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : karan
 * Created : 11/19/2020 08:36:55
 */

package com.cg.capbrading.entity;

import org.junit.*;
import static org.junit.Assert.*;
import com.cg.capbrading.entity.Vendor;

import java.util.ArrayList;
import java.util.List;
import com.cg.capbrading.entity.Product;



public class VendorTest {

	static Vendor vendor;
	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
		vendor = new Vendor();
		List<Product> products = new ArrayList<>();
		Product product = new Product();
		products.add(product);
		vendor.setProducts(products);
	
	}

	/**
	 *
	 * @see com.cg.capbrading.entity.Vendor#getProducts()
	 */
	@Test
	public void getProducts() {
		List<Product> products = vendor.getProducts();
						
							assertTrue("products should be not null and not empty", products != null && !products.isEmpty());
	}

	
}
